#!/usr/bin/env python3
"""
KRK-9 Setup Wizard — Guía interactiva para primer uso.
Ejecutar: python3 setup_wizard.py
"""
import os
import sys
import subprocess
def print_header(text):
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60)
def print_step(step, text):
    print(f"\n[{step}] {text}")
def ask_yes_no(question):
    while True:
        resp = input(f"{question} (s/n): ").strip().lower()
        if resp in ['s', 'si', 'sí', 'y', 'yes']:
            return True
        elif resp in ['n', 'no']:
            return False
        print("  Por favor responde 's' o 'n'")
def ask_input(question, default=""):
    if default:
        prompt = f"{question} [{default}]: "
    else:
        prompt = f"{question}: "
    
    while True:
        value = input(prompt).strip()
        if value:
            return value
        elif default:
            return default
        print("  Este campo es obligatorio. Inténtalo de nuevo.")
def check_dependency(command, name):
    print(f"  Verificando {name}...", end="")
    try:
        subprocess.run([command, "--version"], capture_output=True, check=True)
        print(" ✅")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print(" ❌")
        return False
def main():
    print_header("KRK-9: English Practice Room — Setup Wizard")
    print("\nBienvenido a KRK-9. Este wizard te ayudará a configurar la app.")
    print("Si no sabes qué responder, simplemente presiona Enter (usará valores por defecto).\n")
    
    # Paso 1: Verificar dependencias
    print_step("1/5", "Verificando dependencias")
    deps = {
        "python3": "Python 3.8+",
        "git": "Git",
        "docker": "Docker (opcional, recomendado)"
    }
    
    for cmd, name in deps.items():
        check_dependency(cmd, name)
    
    # Paso 2: Discord Bot Token
    print_step("2/5", "Configuración de Discord")
    print("\nNecesitas un 'Bot Token' de Discord para que la app funcione.")
    print("Si ya tienes uno, pégalo aquí. Si no, visita este enlace:")
    print("  https://github.com/vaseksindelaru/lenguage-room/blob/main/README_USERS.md#cómo-obtener-discord-bot-token\n")
    
    discord_token = ask_input("Discord Bot Token", default="")
    
    # Paso 3: Channel ID y Guild ID
    print_step("3/5", "Configuración del servidor de Discord")
    print("\nNecesitas el ID de tu canal y servidor de Discord.")
    print("Instrucciones: https://github.com/vaseksindelaru/lenguage-room/blob/main/README_USERS.md#cómo-obtener-discord-channel-id-y-guild-id\n")
    
    channel_id = ask_input("Discord Channel ID", default="")
    guild_id = ask_input("Discord Guild (Server) ID", default="")
    
    # Paso 4: Configuración LLM (Ollama vs APIs)
    print_step("4/5", "Configuración de IA (LLM)")
    print("\nKRK-9 puede usar:")
    print("  A) Ollama (gratis, corre en tu computadora, requiere 4GB+ RAM)")
    print("  B) APIs externas (Cerebras, Groq, OpenRouter — gratuitas pero requieren internet)\n")
    
    use_ollama = ask_yes_no("¿Quieres usar Ollama local? (recomendado para principiantes)")
    
    if use_ollama:
        print("\nAsegúrate de tener Ollama instalado: https://ollama.com/download")
        print("Luego ejecuta: ollama pull qwen2.5:3b\n")
        llm_config = {
            "OLLAMA_URL": "http://localhost:11434",
            "CEREBRAS_API_KEY": "",
            "GROQ_API_KEY": "",
            "OPENROUTER_API_KEY": ""
        }
    else:
        print("\nNecesitas al menos una API key gratuita:")
        print("  - Cerebras: https://cereb.as (1M tokens/día gratis)")
        print("  - Groq: https://groq.com (gratis, rápido)")
        print("  - OpenRouter: https://openrouter.ai (modelos :free)\n")
        
        cerebras_key = ask_input("Cerebras API Key (opcional)", default="")
        groq_key = ask_input("Groq API Key (opcional)", default="")
        openrouter_key = ask_input("OpenRouter API Key (opcional)", default="")
        
        llm_config = {
            "OLLAMA_URL": "http://localhost:11434",
            "CEREBRAS_API_KEY": cerebras_key,
            "GROQ_API_KEY": groq_key,
            "OPENROUTER_API_KEY": openrouter_key
        }
    
    # Paso 5: Generar .env
    print_step("5/5", "Generando archivo .env")
    
    env_content = f"""# KRK-9 Configuration
# Generated by setup_wizard.py

# Discord
DISCORD_BOT_TOKEN={discord_token}
CHANNEL_ID={channel_id}
GUILD_ID={guild_id}
VACLAV_USER_ID=0  # Reemplaza con tu Discord User ID

# LLM Providers (llena según corresponda)
OLLAMA_URL={llm_config["OLLAMA_URL"]}
CEREBRAS_API_KEY={llm_config["CEREBRAS_API_KEY"]}
GROQ_API_KEY={llm_config["GROQ_API_KEY"]}
OPENROUTER_API_KEY={llm_config["OPENROUTER_API_KEY"]}

# Audio Server
DISCORD_VOICE_WEBHOOK_URL=

# Opciones
OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct:free
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ Archivo .env creado exitosamente.")
    print("\nAhora puedes ejecutar:")
    print("  ./start.sh        # Para iniciar la app")
    print("  ./start.sh --stop  # Para detenerla")
    print("\n¿Problemas? Consulta:")
    print("  README_USERS.md (para usuarios)")
    print("  README_DEVS.md (para desarrolladores)\n")
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nWizard cancelado. No se guardaron cambios.")
        sys.exit(1)
